[character]
error_symbol = '[✗](bold red)'
success_symbol = '[·](bold green)'
vimcmd_symbol = ''

[directory]
disabled = false
read_only = " 󰌾"
truncation_length = 5
truncate_to_repo = false

[golang]
disabled = false
symbol = " "

[hostname]
disabled = false
ssh_symbol = " "

[elixir]
disabled = false
symbol = " "

[git_branch]
disabled = false
symbol = " "

[lua]
disabled = false
symbol = " "

[nodejs]
disabled = false
symbol = " "

[python]
disabled = false
symbol = " "

[ruby]
disabled = false
symbol = " "

# -------------------------------------
# Everything else is disabled.
# -------------------------------------
[aws]
disabled = true
symbol = "  "

[buf]
disabled = true
symbol = " "

[c]
disabled = true
symbol = " "

[conda]
disabled = true
symbol = " "

[crystal]
disabled = true
symbol = " "

[dart]
disabled = true
symbol = " "

[docker_context]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[fennel]
disabled = true
symbol = " "

[fossil_branch]
disabled = true
symbol = " "

[guix_shell]
disabled = true
symbol = " "

[haskell]
disabled = true
symbol = " "

[haxe]
disabled = true
symbol = " "

[hg_branch]
disabled = true
symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[kotlin]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = "󰍛 "

[meson]
disabled = true
symbol = "󰔷 "

[nim]
disabled = true
symbol = "󰆥 "

[nix_shell]
disabled = true
symbol = " "

[ocaml]
disabled = true
symbol = " "

[os]
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
disabled = true
symbol = "󰏗 "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[pijul_channel]
disabled = true
symbol = " "

[rlang]
disabled = true
symbol = "󰟔 "

[rust]
disabled = true
symbol = " "

[scala]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = " "

[zig]
disabled = true
symbol = " "
